### ISSUE TITLE
Error when saving record when memo is edited.

### ISSUE THREAD

**Issue by C485** [kiredevsandhacks/PrettifyMyWebApi#1]
![image](https://user-images.githubusercontent.com/20170118/211812331-0a8009f5-3748-4dfc-9c3c-ae59e200d186.png)

**Comment by kiredevsandhacks** [comment]
Thx for opening this issue and the clear description! I will fix this in an upcoming update.

**Comment by kiredevsandhacks** [comment]
Fixed. Will be included in next release.
