### ISSUE TITLE
not working correctly in Edge

### ISSUE THREAD

**Issue by KoenJanssensPD** [kiredevsandhacks/PrettifyMyWebApi#3]
In Edge (v119.0.2151.72) , the layout is not correct, and the links are not clickable...

![image](https://github.com/kiredevsandhacks/PrettifyMyWebApi/assets/44767125/e5d82562-5478-4e21-aecd-a458ae771884)

![image](https://github.com/kiredevsandhacks/PrettifyMyWebApi/assets/44767125/73e7846b-22dd-406c-89be-bbf0c77c0385)

**Comment by kiredevsandhacks** [comment]
That is true. For this reason the extension is not (yet) available in the edge store. You can workaround by disabling the JSON viewer add-on in Edge, which is enabled by default. This should fix the issue. 

UPDATE: Navigate to edge://flags/#edge-json-viewer and disable from there

**Comment by KoenJanssensPD** [comment]
> That is true. For this reason the extension is not (yet) available in the edge store. You can workaround by disabling the JSON viewer add-on in Edge, which is enabled by default. This should fix the issue.

seems a valid reason ;-). However, it does not seems "easy" to disable the "msedgeJSONViewer" option... I only found a way to disable it using command line: https://winaero.com/enable-copilot-and-other-hidden-features-in-windows-11-build-23481-dev/#:~:text=Method%203%20(CMD,flag%2Dswitches%2Dend

**Comment by kiredevsandhacks** [comment]
You should be able to just browser to edge://flags/#edge-json-viewer and disable it from there. Unless blocked by policy or something maybe.

**Comment by KoenJanssensPD** [comment]
disabling the edge://flags/#edge-json-viewer option makes the plugin working fine

**Comment by kiredevsandhacks** [comment]
So how did you install the extension exactly? Did you sideload it? Because it's not available on the edge store.

**Comment by KoenJanssensPD** [comment]
> So how did you install the extension exactly? Did you sideload it? Because it's not available on the edge store.

In Edge, I just went to the chrome web store:
 https://chrome.google.com/webstore/detail/prettifymywebapi-for-micr/pcgbnpkpijlcjeleijaaahlonafdlfno/related?utm_source=xrmtc 
 and addid it from there; it just installed as it was a "real" Edge plugin :)

**Comment by kiredevsandhacks** [comment]
ahh ok, I did not know this was possible. In that case I will have to update the description to prevent this issue in the future
