### ISSUE TITLE
Can't edit primary name field?

### ISSUE THREAD

**Issue by bernadonh** [kiredevsandhacks/PrettifyMyWebApi#4]
Thanks for this great tool!

I'm not sure if I have missed something, but it looks like I can't use the tool to update the primary name field of a record? The current value is rendered, but there is no textbox to provide a new value? I am pretty sure this was possible previously. I am seeing this issue in version 1.0.5.0.

**Comment by kiredevsandhacks** [comment]
Thanks for bringing this up! You are correct. I fixed the bug and the package is currently pending approval. Should take a few hours.
